"""aktualizacja migracji

Revision ID: 00a4d048ccb0
Revises: 
Create Date: 2024-05-29 12:59:53.879226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '00a4d048ccb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_toggle_view', sa.Boolean(), nullable=True))
        batch_op.drop_column('can_view_delta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_view_delta', mssql.BIT(), autoincrement=False, nullable=True))
        batch_op.drop_column('can_toggle_view')

    # ### end Alembic commands ###
